#!/usr/bin/env bash
# Install the envctrl privilege shim and a sudoers rule.
# Idempotent: re-running is safe.
set -euo pipefail

SRC="$(cd "$(dirname "$0")" && pwd)/envctrl_shim.py"
DEST="${SHIM_PATH:-/usr/local/libexec/envctrl-shim}"

if [[ ! -f "$SRC" ]]; then
  echo "shim source not found at $SRC" >&2
  exit 1
fi

echo "Installing shim to $DEST"
sudo install -m 0755 "$SRC" "$DEST"

# Determine service user: prefer 'envctrl' if it exists, else current user
SERVICE_USER="${SUDO_USER:-${USER:-pi}}"
SUDOERS_FILE="/etc/sudoers.d/envctrl-shim"

echo "Granting $SERVICE_USER passwordless sudo for the shim"
TMP="$(mktemp)"
cat > "$TMP" <<EOF
# envctrl privilege shim
# Auto-generated by scripts/pi-shim/setup.sh — do not edit by hand.
${SERVICE_USER} ALL=(root) NOPASSWD: ${DEST}
EOF
sudo chown root:root "$TMP"
sudo chmod 0440 "$TMP"
sudo mv "$TMP" "$SUDOERS_FILE"
sudo visudo -c -f "$SUDOERS_FILE" >/dev/null

echo "Done. Test with:"
echo "  echo '{\"sub\":\"list-serial\"}' | sudo $DEST"